#!/bin/bash
# 快速部署指南 - 只需这 3 步！

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🚀 市场活动管理系统 - 快速部署指南（仅需 3 步）              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 你的服务器信息："
echo "  ├─ 地址: 192.168.1.112:5666"
echo "  ├─ 用户: huangshengwei"
echo "  └─ 密码: WKi3,Ly{1g"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 1️⃣  步：连接到服务器"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  你可以通过以下任何方式连接："
echo ""
echo "  ✓ SSH 连接 (如果可用)："
echo "    ssh -p 22 huangshengwei@192.168.1.112"
echo ""
echo "  ✓ 使用 SFTP 客户端 (FileZilla, WinSCP 等):"
echo "    服务器: 192.168.1.112"
echo "    端口: 22 (或其他 SSH 端口)"
echo "    用户: huangshengwei"
echo "    密码: WKi3,Ly{1g"
echo ""
echo "  ✓ 使用服务器的 Web 管理后台"
echo "  ✓ 使用其他远程终端工具"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 2️⃣  步：粘贴这一行命令"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  复制下面的命令，在服务器上执行："
echo ""
cat << 'CMD'
┌─────────────────────────────────────────────────────────────────┐
│  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Ray-NNG/market-activity-system/main/server-install.sh)"  │
└─────────────────────────────────────────────────────────────────┘
CMD
echo ""
echo "  或者如果 curl 不可用，用 wget:"
echo ""
cat << 'CMD'
┌─────────────────────────────────────────────────────────────────┐
│  bash -c "$(wget -O - https://raw.githubusercontent.com/Ray-NNG/market-activity-system/main/server-install.sh)"  │
└─────────────────────────────────────────────────────────────────┘
CMD
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "第 3️⃣  步：等待完成（约 2-3 分钟）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  脚本会自动："
echo "  ✅ 创建项目目录"
echo "  ✅ 下载所有系统文件"
echo "  ✅ 配置 Nginx web 服务器"
echo "  ✅ 重启 web 服务"
echo "  ✅ 验证部署"
echo ""
echo "  完成后会显示访问地址。"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ 完成后，访问以下地址："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🎯 前台报名："
echo "     http://192.168.1.112:5666/market-activity/index.html"
echo ""
echo "  🛠️  后台管理："
echo "     http://192.168.1.112:5666/market-activity/admin.html"
echo ""
echo "  📝 登录账户："
echo "     用户名: admin"
echo "     密码: admin123"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🆘 如果遇到问题："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  错误: bash: curl: command not found"
echo "  💡 解决: 用 wget 替代（见上面的替代命令）"
echo ""
echo "  错误: permission denied"
echo "  💡 解决: 在前面加 sudo，比如："
echo "     sudo bash -c \"...\""
echo ""
echo "  错误: nginx: command not found"
echo "  💡 解决: 需要先安装 Nginx："
echo "     sudo apt-get install nginx  # Ubuntu/Debian"
echo "     sudo yum install nginx      # CentOS/RHEL"
echo ""
echo "  访问时显示 404 或空白页"
echo "  💡 解决: 等待 Nginx 重启完成（约 30 秒）"
echo "     然后检查文件是否在目录中："
echo "     ls -la /var/www/market-activity/"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 更多信息，查看本地文件："
echo "   /Users/ray/WorkBuddy/20260320100957/DIRECT_DEPLOY_GUIDE.md"
echo ""
echo "🎉 准备好了吗？现在就开始部署吧！"
echo ""
